+incdir+../../rtl+../../dep/svlogger
+define+FRISCV_SIM
../common/axi4l_ram.sv
../common/lfsr.sv
./driver.sv
../../rtl/friscv_icache.sv
../../rtl/friscv_icache_fetcher.sv
../../rtl/friscv_icache_blocks.sv
../../rtl/friscv_icache_memctrl.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_scfifo_ram.sv
