+incdir+../../rtl+../../dep/svlogger
+define+FRISCV_SIM
../common/axi4l_ram.sv
../common/lfsr.sv
./driver.sv
../../rtl/friscv_icache.sv
../../rtl/friscv_cache_fetcher.sv
../../rtl/friscv_cache_blocks.sv
../../rtl/friscv_cache_memctrl.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_ram.sv
../../rtl/friscv_rambe.sv
