+incdir+../../rtl+../../dep/svlogger+../../dep/axi-crossbar/rtl
+define+FRISCV_SIM
../common/axi4l_ram.sv
../../rtl/friscv_rv32i_core.sv
../../rtl/friscv_control.sv
../../rtl/friscv_decoder.sv
../../rtl/friscv_alu.sv
../../rtl/friscv_processing.sv
../../rtl/friscv_memfy.sv
../../rtl/friscv_registers.sv
../../rtl/friscv_csr.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_scfifo_ram.sv
../../rtl/friscv_dcache.sv
../../rtl/friscv_icache.sv
../../rtl/friscv_icache_fetcher.sv
../../rtl/friscv_icache_blocks.sv
../../rtl/friscv_icache_memctrl.sv
../../rtl/friscv_apb_interconnect.sv
../../rtl/friscv_io_subsystem.sv
../../rtl/friscv_rv32i_platform.sv
../../rtl/friscv_gpios.sv
../../rtl/friscv_uart.sv
../../dep/axi-crossbar/rtl/axicb_checker.sv
../../dep/axi-crossbar/rtl/axicb_crossbar_lite_top.sv
../../dep/axi-crossbar/rtl/axicb_crossbar_top.sv
../../dep/axi-crossbar/rtl/axicb_mst_if.sv
../../dep/axi-crossbar/rtl/axicb_mst_switch.sv
../../dep/axi-crossbar/rtl/axicb_pipeline.sv
../../dep/axi-crossbar/rtl/axicb_round_robin.sv
../../dep/axi-crossbar/rtl/axicb_round_robin_core.sv
../../dep/axi-crossbar/rtl/axicb_scfifo.sv
../../dep/axi-crossbar/rtl/axicb_scfifo_ram.sv
../../dep/axi-crossbar/rtl/axicb_slv_if.sv
../../dep/axi-crossbar/rtl/axicb_slv_switch.sv
../../dep/axi-crossbar/rtl/axicb_switch_top.sv
