+incdir+../../rtl+../../dep/svlogger
+define+FRISCV_SIM
../common/axi4l_ram.sv
../../rtl/friscv_rv32i.sv
../../rtl/friscv_control.sv
../../rtl/friscv_decoder.sv
../../rtl/friscv_alu.sv
../../rtl/friscv_processing.sv
../../rtl/friscv_memfy.sv
../../rtl/friscv_registers.sv
../../rtl/friscv_csr.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_scfifo_ram.sv
../../rtl/friscv_icache.sv
../../rtl/friscv_icache_fetcher.sv
../../rtl/friscv_icache_lines.sv
../../rtl/friscv_icache_memctrl.sv
