+incdir+../../rtl+../../dep/svlogger+../../dep/axi-crossbar/rtl
+define+FRISCV_SIM
../common/axi4l_ram.sv
../common/lfsr.sv
../../rtl/friscv_rv32i_core.sv
../../rtl/friscv_control.sv
../../rtl/friscv_decoder.sv
../../rtl/friscv_alu.sv
../../rtl/friscv_processing.sv
../../rtl/friscv_memfy.sv
../../rtl/friscv_registers.sv
../../rtl/friscv_csr.sv
../../rtl/friscv_pulser.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_ram.sv
../../rtl/friscv_rambe.sv
../../rtl/friscv_dcache.sv
../../rtl/friscv_icache.sv
../../rtl/friscv_cache_block_fetcher.sv
../../rtl/friscv_cache_prefetcher.sv
../../rtl/friscv_cache_io_fetcher.sv
../../rtl/friscv_cache_ooo_mgt.sv
../../rtl/friscv_cache_pusher.sv
../../rtl/friscv_cache_flusher.sv
../../rtl/friscv_axi_or_tracker.sv
../../rtl/friscv_cache_blocks.sv
../../rtl/friscv_cache_memctrl.sv
../../rtl/friscv_apb_interconnect.sv
../../rtl/friscv_io_subsystem.sv
../../rtl/friscv_rv32i_platform.sv
../../rtl/friscv_gpios.sv
../../rtl/friscv_clint.sv
../../rtl/friscv_bit_sync.sv
../../rtl/friscv_pipeline.sv
../../rtl/friscv_uart.sv
../../rtl/friscv_m_ext.sv
../../rtl/friscv_div.sv
../../rtl/friscv_bus_perf.sv
../../rtl/friscv_mpu.sv
../../rtl/friscv_pmp_region.sv
../../dep/axi-crossbar/rtl/axicb_checker.sv
../../dep/axi-crossbar/rtl/axicb_crossbar_lite_top.sv
../../dep/axi-crossbar/rtl/axicb_crossbar_top.sv
../../dep/axi-crossbar/rtl/axicb_mst_if.sv
../../dep/axi-crossbar/rtl/axicb_mst_switch.sv
../../dep/axi-crossbar/rtl/axicb_pipeline.sv
../../dep/axi-crossbar/rtl/axicb_round_robin.sv
../../dep/axi-crossbar/rtl/axicb_round_robin_core.sv
../../dep/axi-crossbar/rtl/axicb_scfifo.sv
../../dep/axi-crossbar/rtl/axicb_scfifo_ram.sv
../../dep/axi-crossbar/rtl/axicb_slv_if.sv
../../dep/axi-crossbar/rtl/axicb_slv_switch.sv
../../dep/axi-crossbar/rtl/axicb_switch_top.sv
