+incdir+../../rtl
./scram.sv
../../rtl/friscv_rv32i_control.sv
../../rtl/friscv_rv32i_decoder.sv
../../rtl/friscv_rv32i_alu.sv
../../rtl/friscv_rv32i_memfy.sv
../../rtl/friscv_registers.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_scfifo_ram.sv
