+incdir+../../rtl
+define+FRISCV_SIM
./scram.sv
../common/axi4_ram.sv
../../rtl/friscv_rv32i.sv
../../rtl/friscv_control.sv
../../rtl/friscv_decoder.sv
../../rtl/friscv_alu.sv
../../rtl/friscv_processing.sv
../../rtl/friscv_memfy.sv
../../rtl/friscv_registers.sv
../../rtl/friscv_csr.sv
../../rtl/friscv_stats.sv
../../rtl/friscv_apb_interconnect.sv
../../rtl/friscv_gpios.sv
../../rtl/friscv_uart.sv
../../rtl/friscv_io_interfaces.sv
../../rtl/friscv_mem_router.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_scfifo_ram.sv
