+incdir+../../rtl
+define+FRISCV_SIM
./scram.sv
../../rtl/friscv_rv32i_control.sv
../../rtl/friscv_rv32i_decoder.sv
../../rtl/friscv_rv32i_alu.sv
../../rtl/friscv_csr.sv
../../rtl/friscv_rv32i_memfy.sv
../../rtl/friscv_registers.sv
../../rtl/friscv_scfifo.sv
../../rtl/friscv_scfifo_ram.sv
../../rtl/friscv_apb_interconnect.sv
../../rtl/friscv_gpios.sv
../../rtl/friscv_uart.sv
../../rtl/friscv_user_interfaces.sv
