# distributed under the mit license
# https://opensource.org/licenses/mit-license.php

.equ OFF,       0
.equ TOR_RWX,   0x0F
.equ TOR_RW,    0x0B
.equ TOR_RX,    0x0D
.equ NA4_RWX,   0x17
.equ NA4_RW,    0x13
.equ NA4_RX,    0x15
.equ NAPOT_RWX, 0x1F
.equ NAPOT_RW , 0x1B
.equ NAPOT_RX , 0x1D

.equ TOR_LRWX,   0x8F
.equ TOR_LRW,    0x8B
.equ TOR_LRX,    0x8D
.equ NA4_LRWX,   0x97
.equ NA4_LRW,    0x93
.equ NA4_LRX,    0x95
.equ NAPOT_LRWX, 0x9F
.equ NAPOT_LRW , 0x9B
.equ NAPOT_LRX , 0x9D

.equ TOR,       0x08
.equ NA4,       0x10
.equ NAPOT,     0x18
