+incdir+../../rtl
./common/scram.sv
./common/apb_ram.sv
../../rtl/friscv_rv32i.sv
../../rtl/friscv_rv32i_control.sv
../../rtl/friscv_rv32i_decoder.sv
../../rtl/friscv_rv32i_alu.sv
../../rtl/friscv_rv32i_processing.sv
../../rtl/friscv_rv32i_memfy.sv
../../rtl/friscv_registers.sv
