name: FRISCV
on: [push]
jobs:
  lint-code:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install verilator
      - run: ./flow.sh lint
  ci-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: brew install verilator
      - run: iverilog -V
      - run: verilator -V
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim
