name: FRISCV
on: [push]
jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install verilator
      - run: ./flow.sh lint
  Synthesis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install yosys
      - run: ./flow.sh syn
  WBA-Testsuite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: iverilog -V
      - run: brew install verilator
      - run: verilator -V
      - run: brew install md5sha1sum
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim wba-testsuite core icarus
      - run: ./flow.sh sim wba-testsuite core verilator
      - run: ./flow.sh sim wba-testsuite platform icarus
      - run: ./flow.sh sim wba-testsuite platform verilator
  Privilege-Security-Testsuite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: iverilog -V
      - run: brew install verilator
      - run: verilator -V
      - run: brew install md5sha1sum
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim priv_sec-testsuite core icarus
      - run: ./flow.sh sim priv_sec-testsuite core verilator
      - run: ./flow.sh sim priv_sec-testsuite platform icarus
      - run: ./flow.sh sim priv_sec-testsuite platform verilator
  RISCV-Compliance:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: iverilog -V
      - run: brew install verilator
      - run: verilator -V
      - run: brew install md5sha1sum
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim riscv-testsuite core icarus
      - run: ./flow.sh sim riscv-testsuite core verilator
      - run: ./flow.sh sim riscv-testsuite platform icarus
      - run: ./flow.sh sim riscv-testsuite platform verilator
  C-Testsuite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: iverilog -V
      - run: brew install verilator
      - run: verilator -V
      - run: brew install md5sha1sum
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim c-testsuite core icarus
      - run: ./flow.sh sim c-testsuite core verilator
      - run: ./flow.sh sim c-testsuite platform icarus
      - run: ./flow.sh sim c-testsuite
  SV-Testsuite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: iverilog -V
      - run: brew install verilator
      - run: verilator -V
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim sv-testsuite icache
      - run: ./flow.sh sim sv-testsuite dcache
