name: FRISCV
on: [push]
jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install verilator
      - run: ./flow.sh lint
  Synthesis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install yosys
      - run: ./flow.sh syn
  WBA-testsuite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: iverilog -V
      - run: brew install verilator
      - run: verilator -V
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim wba-testsuite
  RISCV-Compliance:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - run: brew install icarus-verilog
     - run: iverilog -V
     - run: brew install verilator
     - run: verilator -V
     - run: git submodule update --init --recursive
     - run: ./flow.sh sim riscv-testsuite
  C-testsuite:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - run: brew install icarus-verilog
     - run: iverilog -V
     - run: brew install verilator
     - run: verilator -V
     - run: git submodule update --init --recursive
     - run: ./flow.sh sim c-testsuite
